# Generated by Django 4.1.4 on 2023-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=1000)),
                ('category_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='pub_date',
        ),
    ]
