# Generated by Django 4.1.4 on 2023-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_details_delete_detail_remove_activities_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='category_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='detail_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
