# Generated by Django 4.1.4 on 2023-01-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_activities_activity_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activity_text',
        ),
        migrations.RemoveField(
            model_name='details',
            name='category_text',
        ),
        migrations.RemoveField(
            model_name='details',
            name='detail_text',
        ),
        migrations.RemoveField(
            model_name='details',
            name='pub_date',
        ),
    ]
