# Generated by Django 4.1.4 on 2023-01-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_activities_activity_text_details_category_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'The Activity', 'verbose_name_plural': 'Activity'},
        ),
    ]
