# Generated by Django 4.1.4 on 2023-01-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_details_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'The Activity', 'verbose_name_plural': 'Activity'},
        ),
        migrations.AddField(
            model_name='activities',
            name='category_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='detail_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
